#!/bin/bash

MAX=$(./run "$@" -r 99999 2>/dev/null | grep -Po '<!>.*\.\.\K([0-9]+)')
if [[ ! "$MAX" ]]
then
    echo "Something went wrong! Perhaps you selected the wrong configuration"
    exit
fi

PARAMETERS=$@
while [[ $1 != "-c" ]]
do
    shift
done
shift

CONFIG_NAME=$1
if [[ ! "$CONFIG_NAME" =~ NoGui ]]
then
    read -p "It seems you are trying to run a batch of simulations with the GUI enabled. Continue (y/n)? " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        exit
    fi
fi

CONFIG_NAME_TRIM=${1/NoGui/}

RESULT_DIR=results
RESULT_DIR_OUT=results/${CONFIG_NAME_TRIM}
SUMMARY_DIR=summary
LOG_DIR=log/${CONFIG_NAME_TRIM}

echo
echo "Exporting summary to '$SUMMARY_DIR/$CONFIG_NAME_TRIM.csv'"
find ${RESULT_DIR} -maxdepth 1 -type f -exec cp {} "${RESULT_DIR_OUT}" \;
scavetool export "$RESULT_DIR_OUT"/"$CONFIG_NAME"_*.{sca,vec} -o "$SUMMARY_DIR/$CONFIG_NAME_TRIM.csv"
find ${RESULT_DIR} -maxdepth 1 -type f -delete
echo
echo "*-*-*-*-*-*-*-*-*-*-"
echo